@api_url = https://api-orderwise-dev.qbitsinc.com/api
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiNzI2ZmM1YjVhZGY4ODBkZTdlODBmOTY0NmNjMmY4NDQ2NDAxZThlZDUwMGUyYzNhNmUyZTUzMDJhZDJhZDgwYjBkN2RiNTJlZGIxZmM0ZGEiLCJpYXQiOjE3NTY5MDY1NDQuMTYwMDg5LCJuYmYiOjE3NTY5MDY1NDQuMTYwMDkxLCJleHAiOjE3ODg0NDI1NDQuMTU4MzEsInN1YiI6IjM1Iiwic2NvcGVzIjpbXX0.Xe87Wz6NQLs1H7C5Ves4BW1QpCeKs8qvwyqvi0t6AL05woFpHzs6bX57uyw91Dxvi68NDR5DWK5PfKWCtUXOq-r5LULSFYo5bSesA0c5X767LQu2kKj-at8j4sZSNTeNoZw7-rwgCEn9vtfnr7hEBKD6r2u8jqvnwcGHCQvu2sq9Eyv0PXuyJBnsN5aH3XquojihnFvLpGm2YIzBLSlKKdRybzhj-wM4WXrPD4Phcbq_7ws6R0elaI1wVYTlDYbp2GAEcgBj1AAH8QmY_IDyVEh4sgBWmoSaChObERlxmx8OQe5ceRJouuntC0QcDY3WPVFw7qm93Qj0K57WxK_nQH43GE-b_6LezYAyL0qQ3abBTx_dQSL43Lw-ydgDLzpMxJVcMeG4xqGLQiZr_N6_tDGgTyTW6PK6CwIvL4dsh9D1psi3qwr1rQLICkGn9QgTv9DYifgGQNpXPPuv9E56WQnfmYv1gfD905PSqmTL_jpABcvN9dfEP94RIFQ_INrCIqdFtpJG0zTVqMUSGLluUKZ7ftP93dwy4b18KYxoHfD0J5k5pv9XI2LJjEI-5ynP61DE-V4TS7Z9-DBcQ0-2FyhgAPV-S5ofRZJEVrtFKviB95MC7EDT-ZAMEABvaQnLQFjWYeiqP-5lQY261zzCL4SkZ1NGXOLtOHJWlhvyfC0

### Obtener configuración de la empresa
GET {{api_url}}/company-configs
Authorization: Bearer {{token}}
Content-Type: application/json

### Obtener pagos de facturas
GET {{api_url}}/invoice-payments?paginate=true&sortBy=id&sortOrder=desc&perPage=20&page=1
Authorization: Bearer {{token}}
Content-Type: application/json


### Obtener pagos de facturas
GET {{api_url}}/invoice-payments?paginate=true&sortBy=id&sortOrder=desc&perPage=10&dataSearch[id]=&dataSearch[name]=&dataSearch[document_number]=&page=1&date=2025-09-05&branch_office_id=1
Authorization: Bearer {{token}}
Content-Type: application/json


# codgio de factura
# fecha y hora del pago no de la factura ()
# metodo de pago
# cliente
# el vendedor si hay si no poner un -
# Los files
